#docker run --name my-mysql -e MYSQL_ROOT_PASSWORD=root_password -e MYSQL_DATABASE=mydatabase -e MYSQL_USER=admin -e MYSQL_PASSWORD=password -p 3307:3306 -d mysql:8.0
#docker run --name my-flask-app -e DB_HOST=my-mysql -e DB_USER=admin -e DB_PASSWORD=password -e DB_NAME=mydatabase -p 8081:8080 --link my-mysql:mysql -v $(pwd):/app -w /app python:3.8 bash -c "pip install -r requirements.txt && python my_app.py"

#docker stop my-flask-app
#docker stop my-mysql

#http://localhost:8081

#docker-compose down
#docker-compose up



version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - my_network


  app:
    image: margarita19/my_app
    ports:
      - "8081:8080"
    environment:
      DB_HOST: docker-db-1
      DB_NAME: mydatabase
      DB_USER: admin
      DB_PASSWORD: password
    depends_on:
      - db
    networks:
      - my_network
volumes:
  mysql_data:

networks:
  my_network:
