name: Build and Test 

# Триггеры для запуска Action
on:
  push:
    branches:
      - main  # Запускается при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускается при создании PR в ветку main

# Описание джоб (задач), которые должны выполняться
jobs:
  build:
    #среда для выполнения
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка исходного кода
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Установка Docker Buildx (расширение для создания многоплатформенных образов)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Шаг 3: Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}  

      # Шаг 4: Сборка Docker-образа
      - name: Build Docker image
        run: docker build . -t margarita19/my_app:latest  

      # Шаг 5: Запуск приложения с использованием docker-compose для выполнения тестов
      - name: Run tests
        run: docker-compose -f docker-compose.yml up --abort-on-container-exit test
